#ifndef OPTION_H
#define OPTION_H
#include "sconf.h"

enum {
    OPTION_MQ_ID = 0,
    OPTION_MQ_PROTO,
    OPTION_MQ_SERVER,
    OPTION_MQ_PORT,
    OPTION_MQ_KEEPALIVE,
    OPTION_MQ_USERNAME,
    OPTION_MQ_PASSWORD,
    OPTION_LIVE_URL,
    OPTION_FTP_ADDRESS,
    OPTION_FTP_USERNAME,
    OPTION_FTP_PASSWORD,
    OPTION_REALTIME_REPORT_PERIOD_MS,
    OPTION_SPEED_LIMIT_THRESHOLD,
    OPTION_RUNINFO_REPORT_SWITCH,
    OPTION_FAULT_REPORT_SWITCH,
    OPTION_FAULT_VIDEO_UPLOAD_SWITCH,
    OPTION_FAULT_REPORT_LIMIT_PER_DAY,
    _OPTION_MAX,
};
enum {
    OPTION_EGUARD_KUNREN_DETECT_ENABLED = 0,
    OPTION_EGUARD_KUNREN_DETECT_TIMEOUT,
    OPTION_EGUARD_DOOR_ZONE_STOPPED_THRESHOLD,
    _OPTION_EGUARD_MAX,
};

extern struct sconf_proto _options[_OPTION_MAX];
extern struct sconf_proto _eguard_options[_OPTION_EGUARD_MAX];

int option_init(void);
#endif